#version 460
#extension GL_GOOGLE_include_directive : enable
#include "../../framework/simplex.glsl"

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

struct PerFrameConstants
{
	mat4 viewMat;
	mat4 inverseViewMat;
	mat4 projectionMat;
	mat4 inverseProjectionMat;
	
	uint width;
	uint height;
	uint frameCounter;
	uint placeholder2;
};

layout(binding = 0) uniform PFC {PerFrameConstants pfc;};
layout(binding = 1, rgba32f) uniform image2D imageOut;
void main()
{
	uvec2 gID = gl_GlobalInvocationID.xy;
	if(gID.x >= pfc.width || gID.y >= pfc.height) return;
	ivec2 p = ivec2(gID);
	float scale = 0.001;
	float timeScale = 0.002;
	float noise_r = snoise(vec4(scale*gID.x, scale*gID.y, timeScale*pfc.frameCounter, 845.2121));
	float noise_g = snoise(vec4(scale*gID.x, scale*gID.y, timeScale*pfc.frameCounter, 789.10221));
	float noise_b = snoise(vec4(scale*gID.x, scale*gID.y, timeScale*pfc.frameCounter, 228.3813));
	vec4 newColor = vec4(noise_r, noise_g, noise_b, 1.0);
	imageStore(imageOut, p, newColor);
}