#version 460
#extension GL_GOOGLE_include_directive : enable

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

struct PerFrameConstants
{
	mat4 viewMat;
	mat4 inverseViewMat;
	mat4 projectionMat;
	mat4 inverseProjectionMat;
	
	uint width;
	uint height;
	uint placeholder1;
	uint placeholder2;
};

layout(binding = 0, set = 0) uniform PFC {PerFrameConstants pfc;};
layout(binding = 1, set = 0, rgba32f) uniform image2D imageOut;
void main()
{
	uvec2 gID = gl_GlobalInvocationID.xy;
	if(gID.xx >= pfc.width || gID.y >= pfc.height) return;
	ivec2 p = ivec2(gID);
	vec4 newColor = vec4(1.0, 0.0, 0.0, 1.0);
	imageStore(imageOut, p, newColor);
}